import = ["~/.config/alacritty/themes/aura.toml"]

[window]
decorations = "Buttonless"
dynamic_padding = true
padding = { x = 18, y = 18 }
dynamic_title = true
option_as_alt = "Both"

[font]
# Run following command on macOS to fix bold fonts in Alacritty 
# defaults write org.alacritty AppleFontSmoothing -int 0
normal.family = "Hack Nerd Font Mono"
size = 18.0

[cursor]
style.shape = "Beam"
style.blinking = "On"
thickness = 0.20

[keyboard]
bindings = [
  { key = "Left", mods = "Option", chars = "\u001BB" },                        # Skip word left
  { key = "Right", mods = "Option", chars = "\u001BF" },                       # Skip word right
  { key = "Left", mods = "Command", chars = "\u001BOH", mode = "AppCursor" },  # Home
  { key = "Right", mods = "Command", chars = "\u001BOF", mode = "AppCursor" }, # End
  { key = "Back", mods = "Command", chars = "\u0015" },                        # Delete line
  { key = "Back", mods = "Option", chars = "\u001B\u007F" },                   # Delete word
]
